### ISSUE TITLE
Why copy cmd to /dep/externalLib1?

### ISSUE THREAD

**Issue by AchimKern** [mir-lab/touchdesigner-summit-2019-external-python#16]
Hey Matthew

following along the video/repo I was wondering why you decided to create/run a .cmd in dep/externalLib1 vs calling pip -r directly from extHelperMOD? 

And have you done any further work on "checking if the cmd needs to be executed"? The current ``` len(os.listdir(python_path)) == 0 ``` check allows only to install a single tox with external dependencies, cause if you e.g. load base_dominant_color.tox first and then e.g. base_hueControl.tox, then base_hueControl.tox will not install its requirements as the python folder is not empty.

cheers
achim

**Comment by raganmd** [comment]
Hey @AchimKern - I've had mixed results running pip directly, especially across platforms. We taught the workshop to a mix of mac and pc users, and creating a file that was then run made sure that we had a break point in the workshop that could get everyone working. When I'm working on pieces for a single platform I'd probably look a different approach here. 

We paused doing too much extra work on the checking to see if the cmd needs to be executed - there was some additional conversation at the summit about what virtual environments would look like and I didn't want to invent a complex schema for handling this if there was already something in the pipe. I haven't heard anything on this front, so it might be worth revisiting.

I think an easy work around would be to add a pulse parameter to force run the installer helper - one of the benefits of having that as a separate file is that you could just prompt the OS to run it as a subprocess call. You could also just construct this same call and issue it directly without all of the rest of the handwaving. 

What I'd really love to see is some proper virtual environment support directly - that would make some large parts of this much easier to wrangle.
